/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pbo.smartinventorymanagement;

import com.pbo.smartinventorymanagement.Databases.DatabaseConnection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import javax.swing.*;
import java.io.FileOutputStream;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author Yazid Yusuf
 */
public class BarangKeluar extends javax.swing.JFrame {
    private String nama;
    private String email;
    private String role;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BarangKeluar.class.getName());

    /**
     * Creates new form BarangKeluar
     */
    public BarangKeluar() {
        initComponents();
        load_table();
        set_barang();
    }

    public BarangKeluar(String nama, String email, String role) {
        initComponents();
        load_table();
        set_barang();

        this.nama = nama;
        this.email = email;
        this.role = role;

        checkRole(role);
    }

    private void checkRole(String role) {
        if (role.equalsIgnoreCase("Admin")) {
            jButton2.setEnabled(true);
            jButton3.setEnabled(true);
            jButton8.setEnabled(true);
        } else if (role.equalsIgnoreCase("Staff")) {
            jButton2.setEnabled(true);
            jButton3.setEnabled(false);
            jButton8.setEnabled(true);
        } else {
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton8.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Smart Inventory - Barang Keluar");
        setResizable(false);
        getContentPane().setBackground(new java.awt.Color(240, 242, 245));

        // Style jLabel1 (Title)
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20));
        jLabel1.setText("SMART INVENTORY MANAGEMENT");
        jLabel1.setForeground(new java.awt.Color(52, 73, 94));

        // Style jLabel7 (Subtitle)
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel7.setText("- BARANG KELUAR -");
        jLabel7.setForeground(new java.awt.Color(41, 128, 185));

        // Style jTable1 - sama persis dengan ListKategori
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 12));
        jTable1.setRowHeight(28);
        jTable1.setGridColor(new java.awt.Color(236, 240, 241));
        jTable1.setShowGrid(true);
        jTable1.setSelectionBackground(new java.awt.Color(52, 152, 219));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable1.getTableHeader().setFont(new java.awt.Font("Segoe UI", 1, 12));
        jTable1.getTableHeader().setBackground(new java.awt.Color(41, 128, 185));
        jTable1.getTableHeader().setForeground(new java.awt.Color(255, 255, 255));
        jTable1.getTableHeader().setPreferredSize(new java.awt.Dimension(0, 35));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 195, 199)));

        // Style Labels - sama persis dengan ListKategori
        jLabel8.setText("ID");
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12));
        jLabel8.setForeground(new java.awt.Color(52, 73, 94));

        jLabel4.setText("Barang");
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12));
        jLabel4.setForeground(new java.awt.Color(52, 73, 94));

        jLabel6.setText("Kuantitas");
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12));
        jLabel6.setForeground(new java.awt.Color(52, 73, 94));

        // Style TextField - sama persis dengan ListKategori
        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 13));
        jTextField4.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 195, 199)),
            javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)
        ));
        jTextField4.setBackground(new java.awt.Color(236, 240, 241));

        // Style ComboBox - styling mirip TextField
        jComboBox2.setFont(new java.awt.Font("Segoe UI", 0, 13));
        jComboBox2.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 195, 199)));

        // Style Spinner - styling mirip TextField
        jSpinner1.setFont(new java.awt.Font("Segoe UI", 0, 13));
        JComponent spinnerEditor = jSpinner1.getEditor();
        if (spinnerEditor instanceof JSpinner.DefaultEditor) {
            JTextField spinnerTextField = ((JSpinner.DefaultEditor) spinnerEditor).getTextField();
            spinnerTextField.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 195, 199)),
                javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)
            ));
            spinnerTextField.setBackground(new java.awt.Color(255, 255, 255));
        }

        // Style Buttons - sama persis dengan ListKategori
        jButton2.setText("Kurangi");
        jButton2.setBackground(new java.awt.Color(231, 76, 60));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12));
        jButton2.setFocusPainted(false);
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setPreferredSize(new java.awt.Dimension(80, 35));
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Edit");
        jButton3.setBackground(new java.awt.Color(241, 196, 15));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12));
        jButton3.setFocusPainted(false);
        jButton3.setBorderPainted(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setPreferredSize(new java.awt.Dimension(80, 35));
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton8.setText("Export");
        jButton8.setBackground(new java.awt.Color(41, 128, 185));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 12));
        jButton8.setFocusPainted(false);
        jButton8.setBorderPainted(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setPreferredSize(new java.awt.Dimension(80, 35));
        jButton8.addActionListener(this::jButton8ActionPerformed);

        jButton5.setText("Clear");
        jButton5.setBackground(new java.awt.Color(149, 165, 166));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12));
        jButton5.setFocusPainted(false);
        jButton5.setBorderPainted(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setPreferredSize(new java.awt.Dimension(80, 35));
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButton7.setText("Dashboard");
        jButton7.setBackground(new java.awt.Color(52, 73, 94));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12));
        jButton7.setFocusPainted(false);
        jButton7.setBorderPainted(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setPreferredSize(new java.awt.Dimension(100, 35));
        jButton7.addActionListener(this::jButton7ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(248, 248, 248))))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(32, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSpinner1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int baris = jTable1.rowAtPoint(evt.getPoint());

        jTextField4.setText(jTable1.getValueAt(baris, 1).toString());
        jComboBox2.setSelectedItem(jTable1.getValueAt(baris, 2).toString());
        jSpinner1.setValue(Integer.parseInt(jTable1.getValueAt(baris, 4).toString()));
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String namaBarang = jComboBox2.getSelectedItem().toString();
            int kuantitas = (Integer) jSpinner1.getValue();

            java.sql.Connection conn = DatabaseConnection.configDB();

            String sqlGet = "SELECT id, stok FROM barang WHERE nama=?";
            java.sql.PreparedStatement psGet = conn.prepareStatement(sqlGet);
            psGet.setString(1, namaBarang);
            java.sql.ResultSet res = psGet.executeQuery();

            int barangId, stok;

            if (res.next()) {
                barangId = res.getInt("id");
                stok = res.getInt("stok");

                // Validasi stok
                if (kuantitas > stok) {
                    JOptionPane.showMessageDialog(
                        this,
                        "Kuantitas melebihi stok tersedia.\nStok saat ini: " + stok,
                        "Stok Tidak Cukup",
                        JOptionPane.WARNING_MESSAGE
                    );
                    return;
                }

            } else {
                JOptionPane.showMessageDialog(null, "Barang tidak ditemukan.");
                return;
            }

            String sqlInsert = "INSERT INTO barang_keluar (barang_id, kuantitas, created_at, updated_at) VALUES (?, ?, NOW(), NOW())";
            java.sql.PreparedStatement psInsert = conn.prepareStatement(sqlInsert);
            psInsert.setInt(1, barangId);
            psInsert.setInt(2, kuantitas);
            psInsert.executeUpdate();

            String sqlUpdate = "UPDATE barang SET stok = stok - ? WHERE id = ?";
            java.sql.PreparedStatement psUpdate = conn.prepareStatement(sqlUpdate);
            psUpdate.setInt(1, kuantitas);
            psUpdate.setInt(2, barangId);
            psUpdate.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal: " + e.getMessage());
        }

        load_table();
        clear_input();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String id = jTextField4.getText();
            String namaBarang = jComboBox2.getSelectedItem().toString();
            int kuantitasBaru = (Integer) jSpinner1.getValue();

            java.sql.Connection conn = DatabaseConnection.configDB();

            String sqlGet = "SELECT id FROM barang WHERE nama=?";
            java.sql.PreparedStatement psGet = conn.prepareStatement(sqlGet);
            psGet.setString(1, namaBarang);
            java.sql.ResultSet res = psGet.executeQuery();

            int barangId;
            if (!res.next()) {
                JOptionPane.showMessageDialog(null, "Barang tidak ditemukan!");
                return;
            }
            barangId = res.getInt("id");

            String sqlOld = "SELECT kuantitas FROM barang_keluar WHERE id=?";
            java.sql.PreparedStatement psOld = conn.prepareStatement(sqlOld);
            psOld.setInt(1, Integer.parseInt(id));
            java.sql.ResultSet resOld = psOld.executeQuery();

            int kuantitasLama = 0;
            if (resOld.next()) {
                kuantitasLama = resOld.getInt("kuantitas");
            }

            String sqlUpdateTrans = "UPDATE barang_keluar SET barang_id=?, kuantitas=?, updated_at=NOW() WHERE id=?";
            java.sql.PreparedStatement psUp = conn.prepareStatement(sqlUpdateTrans);
            psUp.setInt(1, barangId);
            psUp.setInt(2, kuantitasBaru);
            psUp.setInt(3, Integer.parseInt(id));
            psUp.executeUpdate();

            int selisih = kuantitasBaru - kuantitasLama;

            String sqlUpdateStok = "UPDATE barang SET stok = stok - ? WHERE id = ?";
            java.sql.PreparedStatement psStok = conn.prepareStatement(sqlUpdateStok);
            psStok.setInt(1, selisih);
            psStok.setInt(2, barangId);
            psStok.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data berhasil diupdate!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }

        load_table();
        clear_input();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        clear_input();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        new Dashboard(nama, email, role).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        exportToExcel();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void set_barang() {
        try {
            String sql = "SELECT * FROM barang";

            java.sql.Connection conn = DatabaseConnection.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            jComboBox2.addItem("-- Pilih Barang --");
            while(res.next()) {
                jComboBox2.addItem(res.getString(2));
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Mengambil Data: " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new BarangKeluar().setVisible(true));
    }

    private void clear_input() {
        jTextField4.setText(null);
        jComboBox2.setSelectedIndex(0);
        jSpinner1.setValue(0);
    }

    private void load_table() {
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("No");
        model.addColumn("ID");
        model.addColumn("Barang");
        model.addColumn("Kategori");
        model.addColumn("Kuantitas");
        model.addColumn("Dibuat");
        model.addColumn("Diperbarui");

        try {
            int no = 1;

            String sql =
                "SELECT bk.id, b.nama AS barang, k.nama AS kategori, " +
                "bk.kuantitas, bk.created_at, bk.updated_at " +
                "FROM barang_keluar bk " +
                "JOIN barang b ON bk.barang_id = b.id " +
                "JOIN kategori k ON b.kategori_id = k.id";

            java.sql.Connection conn = DatabaseConnection.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            while (res.next()) {
                model.addRow(new Object[]{
                    no++,
                    res.getInt("id"),
                    res.getString("barang"),
                    res.getString("kategori"),
                    res.getInt("kuantitas"),
                    res.getString("created_at"),
                    res.getString("updated_at")
                });
            }

            jTable1.setModel(model);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal load data: " + e.getMessage());
        }
    }

    private void exportToExcel() {
        try {
            Workbook workbook = new XSSFWorkbook();
            Sheet sheet = workbook.createSheet("Data Barang Keluar");

            TableModel model = jTable1.getModel();
            Row headerRow = sheet.createRow(0);

            for (int col = 0; col < model.getColumnCount(); col++) {
                Cell cell = headerRow.createCell(col);
                cell.setCellValue(model.getColumnName(col));
            }

            for (int row = 0; row < model.getRowCount(); row++) {
                Row excelRow = sheet.createRow(row + 1);

                for (int col = 0; col < model.getColumnCount(); col++) {
                    Object value = model.getValueAt(row, col);
                    excelRow.createCell(col).setCellValue(value == null ? "" : value.toString());
                }
            }

            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setSelectedFile(new File("data_barang_keluar.xlsx")); 

            int option = fileChooser.showSaveDialog(null);

            if (option == JFileChooser.APPROVE_OPTION) {
                File file = fileChooser.getSelectedFile();

                FileOutputStream out = new FileOutputStream(file);
                workbook.write(out);
                out.close();
                workbook.close();

                JOptionPane.showMessageDialog(null, "Export laporan barang keluar berhasil!");
            }

        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Export gagal: " + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
