/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pbo.smartinventorymanagement;

import com.pbo.smartinventorymanagement.Databases.DatabaseConnection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import javax.swing.*;
import java.io.FileOutputStream;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author Yazid Yusuf
 */
public class BarangKeluar extends javax.swing.JFrame {
    private String nama;
    private String email;
    private String role;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BarangKeluar.class.getName());

    /**
     * Creates new form BarangKeluar
     */
    public BarangKeluar() {
        initComponents();
        load_table();
        set_barang();
    }

    public BarangKeluar(String nama, String email, String role) {
        initComponents();
        load_table();
        set_barang();
        
        this.nama = nama;
        this.email = email;
        this.role = role;
        
        checkRole(role);
    }
    
    private void checkRole(String role) {
        if (role.equalsIgnoreCase("Admin")) {
            jButton2.setEnabled(true);
            jButton3.setEnabled(true);
            jButton8.setEnabled(true);
        } else if (role.equalsIgnoreCase("Staff")) {
            jButton2.setEnabled(true);
            jButton3.setEnabled(false);
            jButton8.setEnabled(true);
        } else {
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton8.setEnabled(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("SMART INVENTORY MANAGEMENT");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("- BARANG KELUAR -");

        jLabel8.setText("ID");

        jLabel4.setText("Barang");

        jLabel6.setText("Kuantitas");

        jTextField4.setEditable(false);

        jButton2.setText("Kurangi");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Edit");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton8.setText("Export");
        jButton8.addActionListener(this::jButton8ActionPerformed);

        jButton5.setText("Clear");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButton7.setText("Dashboard");
        jButton7.addActionListener(this::jButton7ActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(163, 163, 163))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(248, 248, 248))))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                                                .addComponent(jButton2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton8)
                                                .addGap(108, 108, 108))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(75, 75, 75)
                                                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton7)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)))
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButton7)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton8))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int baris = jTable1.rowAtPoint(evt.getPoint());

        jTextField4.setText(jTable1.getValueAt(baris, 1).toString());
        jComboBox2.setSelectedItem(jTable1.getValueAt(baris, 2).toString());
        jSpinner1.setValue(Integer.parseInt(jTable1.getValueAt(baris, 4).toString()));
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String namaBarang = jComboBox2.getSelectedItem().toString();
            int kuantitas = (Integer) jSpinner1.getValue();

            java.sql.Connection conn = DatabaseConnection.configDB();

            String sqlGet = "SELECT id FROM barang WHERE nama=?";
            java.sql.PreparedStatement psGet = conn.prepareStatement(sqlGet);
            psGet.setString(1, namaBarang);
            java.sql.ResultSet res = psGet.executeQuery();

            int barangId;

            if (res.next()) {
                barangId = res.getInt("id");
            } else {
                JOptionPane.showMessageDialog(null, "Barang tidak ditemukan.");
                return;
            }

            String sqlInsert = "INSERT INTO barang_keluar (barang_id, kuantitas, created_at, updated_at) VALUES (?, ?, NOW(), NOW())";
            java.sql.PreparedStatement psInsert = conn.prepareStatement(sqlInsert);
            psInsert.setInt(1, barangId);
            psInsert.setInt(2, kuantitas);
            psInsert.executeUpdate();

            String sqlUpdate = "UPDATE barang SET stok = stok - ? WHERE id = ?";
            java.sql.PreparedStatement psUpdate = conn.prepareStatement(sqlUpdate);
            psUpdate.setInt(1, kuantitas);
            psUpdate.setInt(2, barangId);
            psUpdate.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal: " + e.getMessage());
        }

        load_table();
        clear_input();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String id = jTextField4.getText();
            String namaBarang = jComboBox2.getSelectedItem().toString();
            int kuantitasBaru = (Integer) jSpinner1.getValue();

            java.sql.Connection conn = DatabaseConnection.configDB();

            String sqlGet = "SELECT id FROM barang WHERE nama=?";
            java.sql.PreparedStatement psGet = conn.prepareStatement(sqlGet);
            psGet.setString(1, namaBarang);
            java.sql.ResultSet res = psGet.executeQuery();

            int barangId;
            if (!res.next()) {
                JOptionPane.showMessageDialog(null, "Barang tidak ditemukan!");
                return;
            }
            barangId = res.getInt("id");

            String sqlOld = "SELECT kuantitas FROM barang_keluar WHERE id=?";
            java.sql.PreparedStatement psOld = conn.prepareStatement(sqlOld);
            psOld.setInt(1, Integer.parseInt(id));
            java.sql.ResultSet resOld = psOld.executeQuery();

            int kuantitasLama = 0;
            if (resOld.next()) {
                kuantitasLama = resOld.getInt("kuantitas");
            }

            String sqlUpdateTrans = "UPDATE barang_keluar SET barang_id=?, kuantitas=?, updated_at=NOW() WHERE id=?";
            java.sql.PreparedStatement psUp = conn.prepareStatement(sqlUpdateTrans);
            psUp.setInt(1, barangId);
            psUp.setInt(2, kuantitasBaru);
            psUp.setInt(3, Integer.parseInt(id));
            psUp.executeUpdate();

            int selisih = kuantitasBaru - kuantitasLama;

            String sqlUpdateStok = "UPDATE barang SET stok = stok - ? WHERE id = ?";
            java.sql.PreparedStatement psStok = conn.prepareStatement(sqlUpdateStok);
            psStok.setInt(1, selisih);
            psStok.setInt(2, barangId);
            psStok.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data berhasil diupdate!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }

        load_table();
        clear_input();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        new Dashboard(nama, email, role).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        exportToExcel();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void set_barang() {
        try {
            String sql = "SELECT * FROM barang";
        
            java.sql.Connection conn = DatabaseConnection.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            jComboBox2.addItem("-- Pilih Barang --");
            while(res.next()) {
                jComboBox2.addItem(res.getString(2));
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Mengambil Data: " + e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BarangKeluar().setVisible(true));
    }

    private void clear_input() {
        jTextField4.setText(null);
        jComboBox2.setSelectedIndex(0);
        jSpinner1.setValue(0);
    }
    
    private void load_table() {
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("No");
        model.addColumn("ID");
        model.addColumn("Barang");
        model.addColumn("Kategori");
        model.addColumn("Kuantitas");
        model.addColumn("Dibuat");
        model.addColumn("Diperbarui");

        try {
            int no = 1;

            String sql =
                "SELECT bk.id, b.nama AS barang, k.nama AS kategori, " +
                "bk.kuantitas, bk.created_at, bk.updated_at " +
                "FROM barang_keluar bk " +
                "JOIN barang b ON bk.barang_id = b.id " +
                "JOIN kategori k ON b.kategori_id = k.id";

            java.sql.Connection conn = DatabaseConnection.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            while (res.next()) {
                model.addRow(new Object[]{
                    no++,
                    res.getInt("id"),
                    res.getString("barang"),
                    res.getString("kategori"),
                    res.getInt("kuantitas"),
                    res.getString("created_at"),
                    res.getString("updated_at")
                });
            }

            jTable1.setModel(model);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal load data: " + e.getMessage());
        }
    }
    
    private void exportToExcel() {
        try {
            Workbook workbook = new XSSFWorkbook();
            Sheet sheet = workbook.createSheet("Data Barang Keluar");

            TableModel model = jTable1.getModel();
            Row headerRow = sheet.createRow(0);

            for (int col = 0; col < model.getColumnCount(); col++) {
                Cell cell = headerRow.createCell(col);
                cell.setCellValue(model.getColumnName(col));
            }

            for (int row = 0; row < model.getRowCount(); row++) {
                Row excelRow = sheet.createRow(row + 1);

                for (int col = 0; col < model.getColumnCount(); col++) {
                    Object value = model.getValueAt(row, col);
                    excelRow.createCell(col).setCellValue(value == null ? "" : value.toString());
                }
            }

            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setSelectedFile(new File("data_barang_keluar.xlsx")); 

            int option = fileChooser.showSaveDialog(null);

            if (option == JFileChooser.APPROVE_OPTION) {
                File file = fileChooser.getSelectedFile();

                FileOutputStream out = new FileOutputStream(file);
                workbook.write(out);
                out.close();
                workbook.close();

                JOptionPane.showMessageDialog(null, "Export laporan barang keluar berhasil!");
            }

        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Export gagal: " + e.getMessage());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
